### ISSUE TITLE
We can only open the URL login page through the HTTP scheme

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#717] opened 2016-03-31 09:32 UTC
The openUrlLogin action causes Cerberus to open the application base URL by adding the `http://` prefix. This hard-coded behavior can be seen at https://github.com/vertigo17/Cerberus/blob/master/source/src/main/java/org/cerberus/service/engine/impl/WebDriverService.java#L934 :
`"http://" + host + (host.endsWith("/") ? uri.replace("/", "") : uri);` 

It could be great to be more flexible and let application to also be reached through the HTTPS scheme.

**Comment by vertigo17** [comment] 2016-04-02 14:48
duplicate of #675

**Closed** 2016-04-02 14:48 UTC
