### ISSUE TITLE
Unable to create user account

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#957] opened 2016-09-29 23:27 UTC
I'm not able to create an user account.
Seeing the logs, I see the message:
[#|2016-09-30T01:25:32.009+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=137;_ThreadName=Thread-2;|2016-09-30 01:25:32 ERROR UserDAO:40 - Unable to execute query : java.sql.SQLException: Field 'UserPreferences' doesn't have a default value

This is blocking.

**Comment by Foudro** [comment] 2016-09-30 07:42
Can we have more information about this bug, because we are not able to reproduce.
Is this done on the old page "UserManager.jsp" or the newly created "UserManager2.jsp"? 

What input do you use when you try to create your User?

**Comment by abourdon** [comment] 2016-10-04 07:59
Hi @gmoita, could you please give us more information about this bug? If not, then we will be forced to close this issue as we cannot reproduce.

Regards,
Aurélien

**Closed** 2016-10-06 00:03 UTC
Labels: bug, critical, Perim : GUIAdministration
