### ISSUE TITLE
Steps with wrong number when adding or deleting

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#827] opened 2016-06-27 10:48 UTC
When adding a step between two other steps the assign number is not correct after saving.
For example, in the image below we just add a step between step 1 and step 2.
The new step should be named step 2 and the step 2 should be step 3 now but the move is not being done after the save:
![image](https://cloud.githubusercontent.com/assets/17747042/16377165/5876ab78-3c5c-11e6-966a-46195ddeb202.png)
But it is executed in the correct order (at least the order we want... not by the step number...):
![image](https://cloud.githubusercontent.com/assets/17747042/16377265/ec42c0b2-3c5c-11e6-8852-418bae50f9e0.png)
We have to go manually on the step number to change it for it to work (for steps to have the correct number).
The same will happend if we delete a step. The steps mumber are not updated.

**Comment by vertigo17** [comment] 2016-06-27 12:09
The order of the execution is correct.
The execution should happen the same way the steps are displayed inside the page.
The issue is duplicate of #825 where the 'old' technical id will no longer be displayed and replaced by the new sort information.
I will close that issue and we will follow up the #825 issue.

**Closed by vertigo17** 2016-06-27 12:09 UTC
