### ISSUE TITLE
Execution result OK with failed step 

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#887] opened 2016-08-09 08:14 UTC
Hello 

My execution result is OK even if a step failed : 
![okwithfa](https://cloud.githubusercontent.com/assets/18569182/17509348/ca896488-5e19-11e6-9ac2-d7f0033839ea.JPG)

Thank you

Cerberus Version : 1.1.5-SNAPSHOT

**Comment by R-Loic** [comment] 2016-08-10 07:16
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=35207949

**Comment by vertigo17** [comment] 2016-08-10 22:49
The issue is coming from a crash of the calculation of:
RESP_ORDER_ID_RIVERSE 		getFromXml
It is still pending...
Can you reproduce that issue systematically ?

**Comment by vertigo17** [comment] 2016-09-24 17:15
Closing the issue as I beleive it cannot be reproduced.
Please reopen with a new case if this is not true.

**Closed by vertigo17** 2016-09-24 17:15 UTC
Labels: Perim : ENGINEProperty
