### ISSUE TITLE
TC Page / Special carac in step makes TC Short Desc disappear

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#732] opened 2016-04-21 08:15 UTC
Cerberus Version : 1.1.4-SNAPSHOT
(Here is the story of some user that I transfer)

tried to put a special caracter in a step description (the 1st step of the TC).
This step is a useStep. there is no special caractere in the original one.
So I customized the title of the step with special caracter (double quote). It worked for a while, till I came back to the TC and noticed everything disappeared after the 1st double quote.
I put it back and saved.

Here come's the fun :
Cerberus took the new step title but deleted the TC description, in which the same double quote and expression was writtent !

How come I write a step description with special caracter and this errases the TC Short desc !!

Cheers,

**Comment by bcivel** [comment] 2016-09-13 21:35
@pfoucray 
I can't explain how it could happened. And as we have no way to reproduce, nor more than one people which raised that, we won't spend time on it.

Regarding the issue with the double quotes, it's solved since this commit 4f54e8ce55ca27d9d834bfe6382e043318f509eb

So I close this issue but don't hesitate to reopen  if you have more information.

Thanks for your contribution
Benoit

**Closed by bcivel** 2016-09-13 21:35 UTC
Labels: Perim : GUITest
