### ISSUE TITLE
Test case update with Step library can create a mess on test cases that use UseStep

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#569] opened 2015-08-19 19:07 UTC
We found a critical issue related to test cases using steps from other test cases.

On a test case that has steps tagged as library, if a step is added before another step that is tagged as library, then the destination test cases (using UseStep) gets changed in a wrong way.

Example:
- One test case (MADIBA_LIB/0002A) has some steps tagged as Library (one is step 8)
- Test case "TAG Commander/0095A" step 1 is tagged as UseStep and copied from MADIBA_LIB/0002A step 8
- On MADIBA_LIB/0002A a step was added before step 8 and after step 7 (new step 8), with the required actions related to the step; this step is almost a copy of step 7, with some differences.
This last action caused "TAG Commander/0095A" step 1 to start using MADIBA_LIB/0002A step 16, which was the last step from the used test case; this was "applied" to all the test cases using UseStep with test case MADIBA_LIB/0002A

This is critical as a complete mess on the database can be caused without knowing and we have no visibility on this.
Test case executions don't record this kind of information.

[Edit]
Hereafter list of todos to fully implement fix:

- [x] add the `sort` column to related database's columns
- [x] deal with the `sort` column from DAO
- [x] add the `sort`attribute from related entities
- [x] add the `sort`attribute from related factories
- [x] deal with the `sort` attribute during automatic execution
- [x] deal with the `sort` attribute during manual execution (jsp and services)
- [x] deal with the `sort` attribute during execution detail (needed by manual execution detail which is not associated to a timestamp)
- [x] deal with the `sort` attribute from current test case page (jsp and servlet)
- [x] deal with the `sort` attribute from beta test case page  (jsp and servlet)
- [x] remove use of legacy related factories methods to fully use the `sort` attribute

**Comment by afnogueira** [comment] 2015-09-18 13:02
Currently working on this issue

**Comment by afnogueira** [comment] 2015-10-02 13:34
@gmoita Please check if the issue is solved.

**Comment by gmoita** [comment] 2015-10-02 15:08
The issue is still happening.
If I add a step before a library step, then the test case step that is using the library get confused.
Still to be resolved.

**Comment by abourdon** [comment] 2016-06-06 13:41
It could be fixed by using a technical id for a used step from the test case. Then, we would add a new column, to the `testcasestep` table and dealing with it to get the used step, instead of dealing with the existing functional one.

@vertigo17 @bcivel Do you agree with that?

**Comment by abourdon** [comment] 2016-06-06 15:28
To sum up: we will use the current Step column as a technical one and add a new column which will gather the step sort number. Note we will impact not only libraries but also step content with action & controls
  
How we will do:

1. Insert the new `Sort` column from the `testcasestep`, `testcasestepaction`, `testcasestepactioncontrol`, `testcasestepactioncontrolexecution`, `testcasestepactionexecution`, `testcasestepexecution` tables, and fill it with the associated `Step` or `Sequence` value
2. Set the engine and CRUD services and servlets to deal with this new value when sorting steps, actions & controls during creation, update & execution
3. Set the current and beta TestCase page to deal with this new value

**Comment by abourdon** [comment] 2016-06-24 00:35
Fix done so I can close issue.

Please check it and tell me if it's ok for you.

Regards,
Aurélien

**Closed by abourdon** 2016-06-24 00:35 UTC
Labels: Awaiting Feedback, bug, critical, Perim : GUITest

**Comment by abourdon** [comment] 2016-06-27 07:27
The new #825 issue has been created to re-have the original natural order for step, action & control numbers.
